### ISSUE TITLE
The App "Trap events from Remotes and Sensors" causes a problem in WallC-S

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#374]
This problem report is essentially the same as the beginning of the now closed issue [#333](https://github.com/Z-Wave-Me/home-automation/issues/333)  I did close that topic because the wallc-s broke down in that experiment.

Now I started again with a brand new walc-s (201614001227) which easily included. The problem is that when I added *Trap events from Remotes and Sensors* the push on either button 2 or button 4 resulted again in WallC-S appeared to be constantly awake in the status screen of Expert UI. I had to use expert menu to send it to sleep again. After removal of the  *Trap events from Remotes and Sensors*, and associating buton pair 2-4 to another switch device, followed by a reboot of the RaspberryPi, the WallC-S was working as expected again.

I think there is something wrong with this app in relation to this device. 

I have extensively reported logs etc under issue #333. The situation there was not essentially different from what I am experiencing now.

**Comment by PoltoS** [comment]
I'm pretty sure the device is sleeping in fact.bthe reason you see it as awake is a bug that was fixed recently.

To confirm it if you see Wakeup Sleep command as Secure, this is the problem described.

Please wait for next release where this is fixed

**Comment by pz1** [comment]
Thanks. I'll wait see. (I was on v2.2.4-rc5 while testing)

**Comment by pz1** [comment]
I have been testing with v2.2.4-rc7.  I did use this [recipe for setup](http://forum.z-wave.me/viewtopic.php?f=3424&t=21965)
Seems it has improved a bit, but sometimes it still hangs. Need a bit more time for experimenting to see under what conditions it hangs. 
Would be nice if someone else could reproduce the recipe to see if it is robust now.

**Comment by pz1** [comment]
I am on v2.2.4-rc9 for a while now, and do not observe the problem anymore.
So closing the issue.
